TRUNCATE TABLE TBL_TODO;
INSERT INTO TBL_TODO VALUES (1, 'TITLE', 'BODY');
INSERT INTO TBL_TODO VALUES (2, 'TITLE-2', 'BODY-2');
INSERT INTO TBL_TODO VALUES (3, 'TITLE-3', 'BODY-3');
INSERT INTO TBL_TODO VALUES (4, 'TITLE-4', 'BODY-4');
